# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing infibranches server ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
     
        script: |
          whoami
          cd Dev/apps/infibranches/
          git init
          git remote add origin https://github.com/Stancovic/reactjs-tutorial-github-actions.git
          git pull origin master
          git add .
          git commit -a
          git status
          npm install
          
    - name: publish package
        run: |
          yarn
          npm run deploy     
          

    
